### PR TITLE
Performance improvements (Fix: #11)

### PR DESCRIPTION
**Pull request by radubogdan**

### CODE REVIEW

**Comment by radubogdan** [comment]
Big win here from speed point of view :) just test it. There are few things you can do to improve it more from the server (serve the gzip, speficy char set, keep-alive, expiry date, Accept-Encoding header)

- [ ]    Fix 404 request to http://rubybelgium.be/assets/img/map-image.png
- [ ]    Minify everything at build (js, css).
- [ ]    Losslessly compress images
- [ ]    Create sprite for images that will not change.
- [ ]    Reduce blocking (order of imported styles)


The only thing that is missing is sprites.

I'll leave it for later. Seems like there is a problem with compass generating them. The code should look something like this (I've restructured the images dir but didn't commit without this sprite change):

```
@import "compass/utilities/sprites";

$sprites-sprite-dimensions: true;
@import "../images/members/*.jpg";
@include all-members-sprites;
```

**Comment by toch** [comment]
@radubogdan thanks a lot for the suggestion. Good idea to do a separated PR for the sprites. I'll look at your code asap.

**Comment by otagi** [comment]
The config file is much cleaner now, yay! ;-)
I'll also look at it tonight.

**Comment by radubogdan** [comment]
I think we gained 2secs in page load, but you decide :D There is still room for more boost

**Comment by toch** [comment]
I tried, it's indeed faster.

Have you measured the difference between loading the previous static version and the new one (I'm not talking about `middleman server`)?

**Comment by radubogdan** [comment]
Of course. I used `middleman build` and serve the /build with a simple python http server.

-- 
Radu-Bogdan Croitoru
dotix @{Freenode, OFTC, Mozilla}
4096R/4BB4E683

On 27 Oct 2015 at 12:44:37, Christophe Philemotte (notifications@github.com) wrote:

Have you measured the difference between loading the previous static version and the new one (I'm not talking about middleman server)?

**Comment by toch** [comment]
Cool. It's ok for me. @otagi ok for you?

**Comment by otagi** [comment]
I haven't had time to run it locally yet. But if everything is still running, we can merge, no problem. ;)

**Comment by toch** [comment]
Thanks @radubogdan :heart:

**Comment by otagi** [comment]
:+1:

**Comment by toch** [comment]
and :shipit: :tada:

**Comment by otagi** [comment]
My latest commits (ca99bc0, 5c47830) have been obliterated by this PR, though. :'(

**Comment by toch** [comment]
djeez ... didn't see that coming.

**Comment by toch** [comment]
I'll find a way to re-apply them. sorry.

**Comment by otagi** [comment]
No worries, it's not breaking anything. I'll try to find time to look at it. ;)

**Comment by radubogdan** [comment]
Thanks guys. Glad is merged :) 

**The boost in speed you'll get from sprites! ** (I expect ~200ms on page load).

I'll make it happen when I'll have some free time.

**Comment by otagi** [comment]
Sorry, my bad. The code is fine, it was just not deployed (and I checked the online version, of course).
Everything is :ok_hand:!

**Comment by toch** [comment]
@otagi is the depoyed one the good one?

**Comment by otagi** [comment]
Yep, I deployed the master an hour ago.

(Let me know what you think about the contact section update.)

**Pull request merged**
