### PR TITLE
Update the projects images and texts

### PR DESCRIPTION
**Pull request by otagi**
- Color corrected images
- New images for RubyBurgers and Slack
- High DPI images
- More descriptive taglines
- Round edges

projects

### CODE REVIEW

**Comment by borisrorsvort** [comment]
Its in one of my project to make a special logo/icons for rubycamp, job board , the slack group and for the brug. But in the mean while Im not a fan of putting images of people directly. I'd rather have clear icon/logo call to go to specific pages (Have a look at https://github.com/brug-be/rubybelgium/issues/40). There you can put image of people.

We're not sure we'll keep the rubycamp bi-yearly.
I'd keep the rubyburger logo also, people recognize it

So not sure  if its the right moment to merge this (Also has merge conflicts)

**Comment by otagi** [comment]
My goal is to slightly improve the current list, which was done way too quickly (by me) at the beginning. Nothing more.

Regarding people pictures:
- It was readily available.
- It emphasizes that "it's more about people" to first-time visitors. 
- It shows a more human, less scary first contact, IMHO. Especially to non geek-white-dudes.

Having said that, I'm eager to see your logos!

RubyCamp: Hence the parentheses. 😉 

I will rebase ASAP to resolve the merge conflicts with #46.

Comments on the new taglines? Better? Worse?

**Comment by borisrorsvort** [comment]
I understand your pov about the people focus, but I think its clearer to have a fixed way to distinguish all the events or project throughout the site or general communication. For making the people focus thing I was going to be inspired by something like http://www.opentechschool.org/foundation/ at the "about the association" section

**Comment by toch** [comment]
My 2 cents, as the logos are not yet there, I'm :+1: for the ppl pictures. As a whole it's more coherent, for now IMHO.

**Comment by toch** [comment]
Just reviewed it again. LGTM as it's a nice improvement of the existing. You can merge for me. (It seems you have a little conflict)

Ofc, that doesn't mean we cannot change it in the future, such as changing the pictures for logos. I personally prefer the version with the pictures, but maybe I can't imagine what could be a version with logos. So, I'm open to discussions.

**Pull request merged**
