### PR TITLE
Add about page

### LINKED ISSUE #71: Create a separate about page
- [x] Create a separate page /about
- [x] Migrate the board members there as well
- [x] Make a list of differents git repos/trello where people can see what we do as the board

### PR DESCRIPTION
**Pull request by borisrorsvort**
Fixes #71
about the association - ruby belgium 20160815

### CODE REVIEW

**Comment by borisrorsvort** [comment]
I'm thinking that we should maybe add a little about the history of the asbl. The historical reason behind, people involved a that time. 
@toch Can you add a little section about that in this PR or after once this one is merged ?

**Comment by toch** [comment]
I like the idea (+ alumni board). I'm going to write it this week.

**Comment by otagi** [comment]
Should we hold off for the history paragraph, or merge ASAP?

**Comment by borisrorsvort** [comment]
@otagi I don't think we are on a hurry, let's wait @toch content as he might want to re-write some of my stuff too

**Comment by toch** [comment]
done

**Comment by toch** [comment]
I missed an error. We should add V.Z.W after A.S.B.L.

**Pull request merged**
