### PR TITLE
Improve railsgirls content strategy

### PR DESCRIPTION
**Pull request by borisrorsvort**
Demo: http://fireman-rolls-60402.bitballoon.com/rails-girls/

### CODE REVIEW

**Comment by oana-sipos** [comment]
@borisrorsvort small suggestion: you are saying ”Our goal is to give enough tools to these women” — but there was no reference to women before, so something seems to be missing / or to be too much. I would keep it simple and say just ”Our goal is to give enough tools to women”.

**Comment by borisrorsvort** [comment]
@oana-sipos your suggestion this uses women ^^ Maybe I should replace it with girls

**Comment by otagi** [comment]
@borisrorsvort Isn't "women" preferable? (or is my joke radar off?)

**Comment by oana-sipos** [comment]
@borisrorsvort the problem in your sentence was not *women* : P it was *these women*, which sounded rather rude : P I would keep *women* or even use Silvana's suggestion (on slack).
So, bluntly:

> Rails Girls was born in Finland, but is nowadays a global, non-profit volunteer community. Our goal is to give enough tools to girls and women to understand technology and provide them with a loveable community to help them build their ideas.

**Comment by borisrorsvort** [comment]
@oana-sipos https://github.com/brug-be/rubybelgium/commit/e2ddc3e12b29d37acbc6d5f49a1151292aa9a7ee

**Pull request merged**
