### PR TITLE
Wip implementation of the job survey results

### LINKED ISSUE #30: Add a Ruby salaries section
As baby step I suggest we copy the same structure as uxBelgium
http://uxdesignin.be/salaries
A page that renders live data from a google form
We can ask almost the same questions.
I suggest, as they did, to exclude freelancers for now, though we can add them in the rubshops section as uxbelgium did too. http://uxdesignin.be/

designer_salaries_survey__ux_designers_in_belgium_2016-03-17_15-49-28

I can suggest the following categories:

- Front-end developer
- Back-end developer
- Full stack developer
- Other

Tech suggestion:

* graph.js http://www.chartjs.org/docs/

Todos:

- [x] Make a Jobs dropdown with Available jobs, Ruby salaries, Ruby shops
- [x] Design the page (with link to the survey form, explanatory text, mulitple sections, ...)
- [x] Add the graphs

### PR DESCRIPTION
**Pull request by borisrorsvort**
@toch Have a look at http://cobbler-alfonso-67104.bitballoon.com/jobs/ruby-salaries-survey for the wip implementation

Queries are in source/assets/javascripts/salaries_graphs.js and based on avg for now. feel free to comment or make some commit on the PR to adapt. You're the stats master :p

fixes #30

### CODE REVIEW

**Comment by toch** [comment]
Nice Job.

On that sample size, and that kind of bounded metrics, average is not a great statistic especially that we do not know if it is normal or not.

So plotting the median is better. I looked quickly in the query reference, and there is no median function as there is one for average. Any idea about that?

**Comment by borisrorsvort** [comment]
@toch No idea. I just copied the one from ux belgium

**Comment by borisrorsvort** [comment]
The idea is to release something. Since you're more aware of the job market and statistics in general than me. Maybe you can take a stab at it on this branch and see what we can use and make sense using these tool.
But lets ships something even small

**Comment by toch** [comment]
Well it's good enough to be shipped like this then. :+1:

**Pull request merged**
