### PR TITLE
New banner

### LINKED ISSUE #5: Change header image
It would cost us 180 euro per year to use a picture of the Atomium :/

### PR DESCRIPTION
**Pull request by toch**
Fixes #5

### CODE REVIEW

**Comment by toch** [comment]
@otagi @brug-be/owners what do you think?
screenshot from 2015-10-19 23 48 16

**Comment by joren** [comment]
Nice. I really like it!

--
Joren

**Comment by ys** [comment]
Good choice

**Comment by otagi** [comment]
Great picture! There is still some white-on-white text, depending on the window width (with the city hall tower), But it's fairly readable nonetheless.

The credits caption is a nice touch.

Maybe add some bottom margin to the `h2` where the `h3` were removed? The former currently has `15px`, and the latter `75px`, so less whitespace. What do you think?

**Comment by toch** [comment]
Just pushed a few minor changes:

* more space under project title
* better visibility of header title

ok for you?

**Comment by otagi** [comment]
Neat!

I applied your margin to the events title as well.

Time for a merge!

**Comment by otagi** [comment]
The new master is deployed.

**Comment by toch** [comment]
:shipit: :+1: thX!

**Comment by joren** [comment]
:+1: I've contacted the Atomium people we changed the picture.

**Comment by toch** [comment]
@joren thanks!

**Comment by otagi** [comment]
:+1:

**Pull request merged**
