### PR TITLE
Update to middleman v4

### PR DESCRIPTION
**Pull request by borisrorsvort**

### CODE REVIEW

**Comment by dantesolis** [comment]
I'm almost done, sorry peeps, got a bit side track with applying for jobs. Although wanted to run some stuff by you guys, I was thinking of moving the contact form to a typeform format and leave it  where is at now or should I  just leave it as it is now?

**Comment by borisrorsvort** [comment]
@dantesolis Wrong place for comment 😉  I'd leave the contact as a mailto: for now. baby steps.

**Comment by dantesolis** [comment]
Ok, then I'll send that  PR today or tomorrow. Thanks. 

Comments in the #slack?

**Comment by borisrorsvort** [comment]
No here https://github.com/brug-be/rubybelgium/issues/27

**Comment by dantesolis** [comment]
oops thanks. ;)

**Pull request merged**
